# Stage 1: Build
FROM python:3.11-alpine AS builder
RUN apk add --no-cache gcc musl-dev linux-headers postgresql-dev
WORKDIR /app
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Stage 2: Final Image
FROM python:3.11-alpine
RUN apk add --no-cache libpq
WORKDIR /app
COPY --from=builder /usr/local/lib/python3.11/site-packages /usr/local/lib/python3.11/site-packages
COPY --from=builder /usr/local/bin /usr/local/bin
COPY . .
EXPOSE 5000
CMD ["python", "-u", "dispatcher.py"]
